### ISSUE TITLE
Cannot create PoolableConnectionFactory

### ISSUE THREAD

**Issue by NicoTexas** [TIBCOSoftware/js-docker#3] opened 2017-01-14 18:14 UTC
I just ran docker-compose up without any change to the project.
Docker container is getting built, Postgres database is being initialized, Web app is starting but fails to connect to the database.
`jasperserver_1  | 14-Jan-2017 18:07:47.401 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service Catalina
jasperserver_1  | 14-Jan-2017 18:07:47.401 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet Engine: Apache Tomcat/8.0.39
jasperserver_1  | 14-Jan-2017 18:07:47.410 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory /usr/local/tomcat/webapps/jasperserver-pro
jasperserver_1  | 14-Jan-2017 18:08:04.947 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger
 for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
jasperserver_1  | 2017-01-14 18:08:11,531 ERROR JDBCExceptionReporter,localhost-startStop-1:101 - Cannot create PoolableConnectionFactory (Connection refused. Check that the hostname and port are correct and that th
e postmaster is accepting TCP/IP connections.)`

I am using Docker for Windows
Version 1.13.0-rc6-beta36 (9696)
Channel: Beta
64a715b

I attached the entire log file
[jasperdocker.txt](https://github.com/TIBCOSoftware/js-docker/files/706123/jasperdocker.txt)

thanks

**Comment by NicoTexas** [comment] 2017-01-14 18:48
Note that I have been able to get the app to start and connect to the database by stopping the containers, set JRS_DBCONFIG_REGEN to true in the .env file and then relaunch compose-up
I suspect there is an issue in the initial run of entrypoint.sh

**Comment by nataliiakel** [comment] 2017-01-17 00:42
@NicoTexas, thanks for the information. We were not able to reproduce the issue in the house, but it's forwarded to our development team for further investigation.

**Comment by nataliiakel** [comment] 2017-01-19 23:25
We'll close the issue since there's a workaround.

**Comment by nataliiakel** [comment] 2017-01-19 23:25
We'll close the issue since there's a workaround.

**Closed by nataliiakel** 2017-01-19 23:25 UTC
